### ISSUE TITLE
Help with error when running demo

### ISSUE THREAD

**Issue by ximenesfel** [yysijie/st-gcn#52] opened 2018-06-15 21:55 UTC
### Code version (Git Hash) and PyTorch version:
Branch: master
Pytorch: 0.4.0
### Dataset used
--
### Expected behavior
Save the video in data/demo_result/
### Actual behavior
/home/ximenes/.virtualenvs/gcn/bin/python3.6 /home/ximenes/PycharmProjects/graph/st-gcn/main.py demo --openpose /home/ximenes/openpose/build/ --video /home/ximenes/Desktop/openpose/videos/dataset/S001C001P001R001A001_rgb.avi
Traceback (most recent call last):
  File "/home/ximenes/PycharmProjects/graph/st-gcn/main.py", line 29, in <module>
    p = Processor(sys.argv[2:])
  File "/home/ximenes/PycharmProjects/graph/st-gcn/processor/io.py", line 26, in __init__
    self.init_environment()
  File "/home/ximenes/PycharmProjects/graph/st-gcn/processor/io.py", line 57, in init_environment
    self.io.save_arg(self.arg)
  File "/home/ximenes/.virtualenvs/gcn/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg/torchlight/io.py", line 118, in save_arg
FileNotFoundError: [Errno 2] No such file or directory: '{self.work_dir}/config.yaml'

### Steps to reproduce the behavior
A follow the instructions to install the libraries

My environment
![screenshot from 2018-06-15 18-49-48](https://user-images.githubusercontent.com/12705275/41491012-11dbeeec-70cd-11e8-8593-13485c9a73f3.png)

Command:
`/home/ximenes/.virtualenvs/gcn/bin/python3.6 /home/ximenes/PycharmProjects/graph/st-gcn/main.py demo --openpose /home/ximenes/openpose/build/ --video /home/ximenes/Desktop/openpose/videos/dataset/S001C001P001R001A001_rgb.avi`
### Other comments
Openpose is working corretly in my machine.

**Comment by yysijie** [comment] 2018-06-16 07:11
Hi, @ximenesfel, you should first change the directory to the project root folder.

**Comment by ximenesfel** [comment] 2018-06-16 10:36
Hi @yysijie. Thanks for your quick response. If I understood correctly, I changed the working directory to root folder but I having the same error.

![screenshot from 2018-06-16 07-32-05](https://user-images.githubusercontent.com/12705275/41497980-bbffb29a-7137-11e8-89f5-7ccc87f97a60.png)

This work_dir variable refers to work_dir folder in the project?

**Comment by Zzoey** [comment] 2018-06-18 18:11
@yysijie I get this error when I run ntu_gendata.py. Repo structure is maintained as it is, I am not sure why this error occurs   
import tools
ModuleNotFoundError: No module named 'tools'

**Comment by yysijie** [comment] 2018-07-05 06:51
@ximenesfel,
Sorry for the late reply.
I think this is a duplicate of [this issue](https://github.com/yysijie/st-gcn/issues/60). 
Could you move to there and tell me your python version?

**Closed** 2018-07-05 06:52 UTC

**Comment by yysijie** [comment] 2018-07-06 11:07
@ximenesfel ,
I think it is caused by the f-strings, which is a new feature of python3.6.
We removed all f-strings in the codebase. I think it will help.
